spring:
 datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:test
   username: sa
   password: '{cipher}AQBy8PnVAIvT4gPBUrymUT3fr1Gp+tf3cmz1bJuQ+rlRprt2esrQobkDbQqFte54RThWCMg92j2PqaKYTMiALg3SJ+vXL4BbXiqcV1hQWG3YSFKLXTP4G3KNOik/BhxCUBtWONV7ZogQsjHvmgX4IsgDbwn3B1t8dmiqlPhKceHbLqSESk9jf7ogbec+tgw33S7pEku6mlkBocenwevh/QaenQKfBvGMt+wyr5+a4m3bSSSbcHwh2OkhYN9ctnA0HtouqWs4WVoFPM4YLLZ0qdu3ky2kU8ZGurBYrnlWQI+PdOPMwgVCSKbKZ7fWjD+Qx3Uk7thrMbxHFz7x+U5AdCaroQn5oGNHf9UUJ0zbtBsuBviLI3apz6HU7Ps+ZRP9t1I='

jwt:
  secret: '{cipher}AQADONtvVxFEYsBOmQ3H3aVHgCQ9P7Sk/L2lMYmm/SLPffRta+2ZsTZexT2njxpPIhm4IB5ETz1Hp0qhx++6hbk6L4iP2ZYwXbLnrauzNWDhbdwRbE58PnfnV9fymrqfj7+u0ldscWv5pr2xACXd7BLJ4Ry6CbajlgHFC1LvlaUTRudL/ieADByb/xMhVGEL2cL876UOgTCOaTjVg2SQfHvCYx8Ai/Ihv+afwDg/ncoGUDpdhFBRdUNibEgIrwbzcoGvk+bcvXQSIE41sYyNC3WNqton1bapZ8OYyBx5Y3gTez+K6LQXpa4eBko3hyuseVxPz8ILd8dXiZIQBaAe8/98fCF0drbo18xFUxUtBPw8oukulWAptSmMXJB90hjaBcuRZa66kZfQnrc0ULpmIHj5W2+LWPDao3ESEfCY71j3BHLcZSkCtLegj4/3Zt0LypvFfmL2ATONX8+G12WAEuWM'
  expiration_time : 8640000

gateway:
  ip: 192.168.0.17